name: Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache LLVM and Clang
      id: cache-llvm
      uses: actions/cache@v3
      with:
        path: |
          C:/Program Files/LLVM
          ./llvm
        key: llvm-15
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "15"
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}
    - name: Setup NASM
      uses: ilammy/setup-nasm@v1
      with:
        from-source: true
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Install python dependencies
      run: python -m pip install pyjson5
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: bash
      run: ./build.py -m release -t tests/hello.c
